### ISSUE TITLE
Missing key in mlora.json when training and evaluating multi-task

### ISSUE THREAD

**Issue by Edmund-Lai** [TUDB-Labs/MixLoRA#3] opened 2024-07-19 09:03 UTC
After executing `python ./launch.py gen --template mixlora --tasks "arc-c;arc-e;boolq;obqa;piqa" --multi_task True --adapter_name mixlora` to generate `mlora.json`, I tried `python ./launch.py run --base_model <Path to Your Base Model>` for training and evaluating on multi-task setting.

Then I got the following error message:
```
Traceback (most recent call last):
  File ".../mlora/mlora.py", line 268, in <module>
    mlora.train(mlora.Dispatcher(config, tokenizer), model,
  File ".../mlora/mlora/dispatcher.py", line 201, in __init__
    dataload_function=lora["dataloader"],
KeyError: 'dataloader'
```
I checked the code in `dispatcher.py`, the dataloader should be a `Callable` object. How can I fix this error?

Thanks.

**Comment by mikecovlee** [comment] 2024-07-19 09:07
Which version of m-LoRA you are using with?

**Comment by Edmund-Lai** [comment] 2024-07-19 09:11
> Which version of m-LoRA you are using with?

0.3.2, same as the README mentioned.

**Comment by mikecovlee** [comment] 2024-07-19 09:16
All our experiments were conducted under version 0.3.2. Based on your description, I cannot reproduce this problem. There may be some problems with your Git repository. You can try using the latest version. If the problem persists, you can add me on WeChat (ID: mikecovlee) to discuss in detail.

**Comment by mikecovlee** [comment] 2024-07-29 09:13
Closing issue because no further response.

**Closed as completed by mikecovlee** 2024-07-29 09:13 UTC
